### ISSUE TITLE
Please provide a screenshot of how this looks

### ISSUE THREAD

**Issue by luzpaz** [infojunkie/MantisBT-Slack#14]
Thanks!

**Comment by infojunkie** [comment]
![screenshot-mantis meedan net 2015-11-12 10-52-51](https://cloud.githubusercontent.com/assets/92977/11127919/9ccf4a8a-892b-11e5-9937-069a8995679c.png)
![screenshot-meedan slack com 2015-11-12 10-50-33](https://cloud.githubusercontent.com/assets/92977/11127920/9ccff250-892b-11e5-8b1f-18e787de36e8.png)

is this what you mean?
