### ISSUE TITLE
Mention User and channel

### ISSUE THREAD

**Issue by nasirkhan** [infojunkie/MantisBT-Slack#15]
Slack Incoming Web Hook doc says that, there is a way to mention the user and channels, it would be great if you please enable this feature.

> By default, Slack will not linkify channel names (starting with a '#') and usernames (starting with an '@'). You can enable this behavior by passing link_names=1 as an argument. This behavior is always enabled in parse=full mode (see below).

https://api.slack.com/docs/formatting

**Comment by infojunkie** [comment]
Done!

**Comment by nasirkhan** [comment]
thanks :+1:

**Comment by infojunkie** [comment]
FYI, I've added a "Link to names" option to the Slack config and made it OFF by default. In practice, we noticed that having parsed names was generating too many unneeded Slack notifications.
