### ISSUE TITLE
Object of class BugData could not be converted to string - when changing status

### ISSUE THREAD

**Issue by rysmith25** [infojunkie/MantisBT-Slack#22]
MantisBT works perfect before I add this plugin.  After I install the plugin, everything works including the plugin, but there is a little error message that I get when changing the status or changing who it is assigned to.  
![class bugdata could not be converted to string](https://cloud.githubusercontent.com/assets/14784106/17124665/d16fb2d0-52ba-11e6-87a5-92112136b7df.jpg)

**Comment by RWarnecke** [comment]
I have the same issue with mantis 1.3.0 and the actually commit of MantisBT-Slack

**Comment by RWarnecke** [comment]
I found a work around. Put theses lines into the config/config.php and it works :

// --- Error Logging ---
$g_display_errors = array(
	E_USER_ERROR   => DISPLAY_ERROR_HALT,
	E_USER_WARNING => DISPLAY_ERROR_HALT,
	E_WARNING      => DISPLAY_ERROR_INLINE,
);
$g_show_detailed_errors = ON;

There come no error and the slack message was send. It works under PHP 5.6.

**Comment by rysmith25** [comment]
Thank you Rolf.  I also got it to work by using Mantis 1.2.

**Comment by infojunkie** [comment]
Thanks @RWarnecke and @rysmith25 for the report and workaround. I will try to replicate to find the root  cause.

**Comment by secustor** [comment]
@infojunkie I can confirm this issue for MantisBT 2.0 beta2 too. 

greetings

**Comment by infojunkie** [comment]
Fixed on `master`.
