### ISSUE TITLE
don't leak private information

### ISSUE THREAD

**Issue by RWarnecke** [infojunkie/MantisBT-Slack#32]
I had the same problem such as issue #26. I use the actually pull here from GitHub and MantisBT Version 2.3.0.

**Comment by infojunkie** [comment]
The original issue is closed because it was fixed. What is different in your case?

**Comment by RWarnecke** [comment]
The same problem as the old issue #26 . If I wrote a private message to an issue. The message was pushed to the slack channel. Also if I open a new issues with the private flag and I save it, the issue was showing in the slack channel.

**Comment by infojunkie** [comment]
I am unfortuantely unable to reproduce this. Can you help with debugging? In `Slack.php`, the attribute `$this->skip` should be turned ON when the `$bug->view_state` or `$bugnote->view_state` are set to `VS_PRIVATE`. That's the condition that I check for to skip sending notifications.

**Comment by RWarnecke** [comment]
I didn't know why, but I delete the slack plugin and installed it new. Then no private informations are leaked into slack. Thank you for your help.

**Comment by infojunkie** [comment]
My favorite kind of bugs! Thanks for updating.
