### ISSUE TITLE
Notification not sent

### ISSUE THREAD

**Issue by PeuX** [infojunkie/MantisBT-Slack#35]
Hi,
First thanks for the plugin 👍 !
on my installation ( Mantis 2.5.1, Mattermost 3.9 ) i've got some issue : no notification sended.
When i watch the curl return from mattermost i saw a parse_error.

For bypass the issue i change this (Slack.php L: 294):
`$data = array('payload' => json_encode($payload));`
to
`$data = 'payload='.json_encode($payload);`

hope this help some people :)

Bye :)

**Comment by infojunkie** [comment]
Thanks for the report. I'm not sure if this is a difference between Mattermost and Slack, so let's wait for confirmations before incorporating this change.

**Comment by TomaszDom** [comment]
This fix definitely works for RocketChat, thanks!
