### ISSUE TITLE
bug_report_update function missing $bug = bug_get($bug_id);

### ISSUE THREAD

**Issue by TomaszDom** [infojunkie/MantisBT-Slack#37]
This plugin fails to work correctly when you update a bug in Mantis, all other situations (create, delete, add note, edit note, delete note) work fine.

When I update a bug Mantis complains about missing bug "0" and data sent to Slack is always the same generic information about bug 000000 with no details.

The bug_report_update function in Slack.php is missing this:

`$bug = bug_get($bug_id);`

With this fix in place, the warning is gone and webhook data about updated bugs is correct.

**Comment by infojunkie** [comment]
What version of Mantis are you using? We've been using this plugin for years, literally, and we've been receiving update notifications.

**Comment by TomaszDom** [comment]
This is legacy system, version 1.2.x with PHP 5.3.x, 

I'm using the 1.2.x branch of the plugin with RocketChat instead of Slack, it works fine after fixing the missing bug_id value in the bug_report_update function and replacing line:

`$data = array('payload' => json_encode($payload));`

with

`$data = 'payload='.json_encode($payload);`

**Comment by TomaszDom** [comment]
Wait, maybe you misunderstand, I AM receiving notifications, but when a bug gets edited, then the notification is always about a non-existant bug 000000 with no other real values from any other fields. This is because the bug_id value is missing from that function. I've debugged this, take a look at the code.

I'm glad that the plugin works great for you and now it works great for me too! Thanks for creating it it.

**Comment by infojunkie** [comment]
I see, thanks. I will review the `1.2.x` branch and add that fix.

**Comment by infojunkie** [comment]
Fixed on `1.2.x` branch as per https://github.com/infojunkie/MantisBT-Slack/commit/b63b5a145ef50a4d2f068dcf60299f4f50ff0142
