### ISSUE TITLE
APPLICATION ERROR #plugin_Slack_ERROR_CURL

### ISSUE THREAD

**Issue by Srikanthparimi** [infojunkie/MantisBT-Slack#38]
This was the issue(The request to Slack didn't go through. Check your webhook URL. Also make sure there are no unusual characters in your bot name or bot icon settings. ) I was going through. According to some article I tried all the ways by adding the peace of code on to the slack.php file (if ($result !== 'ok') {
            echo curl_error($ch);
            echo '<br>';
            echo curl_errno($ch);
            echo '<br>'; ) But hard luck. Nothing changed but I am able to see a small notification saying that [ Previous non-fatal errors occurred. Page contents follow.
Connection timed out after 5001 milliseconds
28 ] But the connection is good 
  
I checked weather the webhook URL is working or not its perfectly working as i curl the url with Json file could able to see it on slack channel. Please some one help me to fix this issue.

**Comment by infojunkie** [comment]
It's hard to debug connection issues remotely. I suggest you:
a) ensure that php curl functions are working for you in general (e.g. in a separate test php script)
b) if so, change the `curl_setopt` calls in `Slack.php` to catch the cause of the timeout error

**Comment by infojunkie** [comment]
Closing for lack of feedback.
