### ISSUE TITLE
Option to skip notifications for private issues and notes

### ISSUE THREAD

**Issue by clandestina2** [infojunkie/MantisBT-Slack#44]
Hello, I have followed every step of the configuration and I can't make it work.
Any guideline on how to debug the plugin?

Thanks

**Comment by infojunkie** [comment]
To debug, you can turn on logging as per https://www.mantisbt.org/docs/master/en-US/Admin_Guide/html/admin.config.logging.html and then insert logging instructions in the file `Slack.php`.

But what does
> and I can't make it work.
mean? Specifically, what is not working? 

- Does the plugin show up in the "Installed Plugins" section of `/manage_plugin_page.php` ?
- Does the plugin settings pag show up at `/plugin.php?page=Slack/config_page` ?

**Comment by clandestina2** [comment]
Yes the plugin show up in the installed plugins section, I have everything configures including
- webhook url, slack channels, slack usernames

**Comment by infojunkie** [comment]
OK great, then you should be able to insert some logs at https://github.com/infojunkie/MantisBT-Slack/blob/master/Slack.php#L265 for example, to ensure that the execution reaches the right place. If not, go up the call chain until you reach `bug_report`, `bug_update`, etc.

What's the Mantis version are you using?

**Comment by infojunkie** [comment]
Wrong button :-)

**Comment by clandestina2** [comment]
I'm using the latest stable version 2.11.1
can you send me the lines to insert for the log? tnks!

**Comment by infojunkie** [comment]
Note that I haven't tested the plugin with Mantis > 2.5, and I don't expect to do so in the short term - so I am grateful for your help here!

**Comment by clandestina2** [comment]
I put plugin_log_event($msg);
        plugin_log_event($channel);
        plugin_log_event($webhook);
right after line 265 and in the log every parameter is correct 
any idea?

**Comment by infojunkie** [comment]
No idea, but I would continue debugging at https://github.com/infojunkie/MantisBT-Slack/blob/master/Slack.php#L299 and logging the result there.

**Comment by clandestina2** [comment]
Ok so I commented line 266
function notify($msg, $webhook, $channel, $attachment = FALSE) {
        //if ($this->skip) return;
        if (empty($channel)) return;
        if (empty($webhook)) return;

and everything is working now, I'm getting the messages in slack =)

**Comment by infojunkie** [comment]
Nice! Can you find out which assignment of `$this->skip` causes this? There must be a difference in the sequence of events between Mantis 2.5.x and 2.11.x

**Comment by clandestina2** [comment]
ok, so further analysis, all my problems were due to the visibility of the bug and notes.
reviewing the conditions for the $this->skip if anything is private then the notification is skipped
since I want notification on all the bugs I removed the verification on every action

**Comment by infojunkie** [comment]
Thanks a lot for the analysis - feel free to convert this to a feature request to make optional the skipping on private content.

**Comment by clandestina2** [comment]
I created 2 new options, works great!

![2018-02-27_0-17-37](https://user-images.githubusercontent.com/36859991/36708828-c84ad168-1b53-11e8-91eb-21bd76be95a1.png)

**Comment by infojunkie** [comment]
Woooo plz PR !

**Comment by clandestina2** [comment]
I'm trying to do a push of the changes but I get permission denied (using sourcetree)

**Comment by infojunkie** [comment]
https://yangsu.github.io/pull-request-tutorial/

**Comment by infojunkie** [comment]
Please note that I will merge the two checkboxes into a single "Skip notification on private content" to a) avoid too many settings, and b) be symmetrical with the bulk actions option.

**Comment by clandestina2** [comment]
I'm trying to publish a branch and keep getting "Authentication failed. You may not have permission to access the repository or the repository may have been archived"

**Comment by infojunkie** [comment]
You are problably trying to push to my repository. You need to 1) fork the repo, 2) push fixes to your `master` or other branch, then 3) submit a PR to my repo. But don't worry about it too much I can make a commit like what you're doing above... the analysis was the important part.

**Comment by infojunkie** [comment]
Merged your PR after some changes - thanks!
