### ISSUE TITLE
Support subprojects

### ISSUE THREAD

**Issue by worldofmadness** [infojunkie/MantisBT-Slack#47]
how do i get it to pick up the subcategory ID when they submit a ticket so we know wif its for say live or dev client?

**Comment by infojunkie** [comment]
If I understand correctly, you would like to send the subcategory as a field in the Slack notification?

**Comment by worldofmadness** [comment]
Yes thats right as we need the devs to know if its live or in staging server

**Comment by infojunkie** [comment]
Can you plz explain more what you mean by subcategory? I haven't found this word in the Mantis documentation. I need to understand how are you creating subcategories in order for me to support them. Include screenshots if you can.

**Comment by worldofmadness** [comment]
Sorry its sub catigories

**Comment by worldofmadness** [comment]
In mantis you  sub projects dan i need to read

**Comment by infojunkie** [comment]
OK I'll make a local setup with subprojects and try it out.

**Comment by infojunkie** [comment]
No need to close it: I still intend to work on it.

**Comment by worldofmadness** [comment]
closed it as seems it got it to now see what i wanted after i reinstalled when i updated mantisbt the the catigories seem to now be showing. hence why i closed it :D
