### ISSUE TITLE
os, os_build, platform, version, not showing up in the slack side

### ISSUE THREAD

**Issue by worldofmadness** [infojunkie/MantisBT-Slack#48]
os, os_build, platform, version, seem to not show up in the slick side any ideas ?

**Comment by infojunkie** [comment]
I never tested those haha - you would do me a great favor by debugging it

**Comment by worldofmadness** [comment]
i have added a custom box to cover this one so they can choose on the custom one instead seems to work fin that way

**Comment by worldofmadness** [comment]
got it all working
