### ISSUE TITLE
Notifications settings

### ISSUE THREAD

**Issue by kajetant** [infojunkie/MantisBT-Slack#49]
Right now Slack notifications are being sent when:
- Issues are created
- Issue status is changed
- Notes are added.
- Issue assignment is changed. 
- An issue is deleted
- An issue is moved to the mapped project. (At this point there is no notification when an issue is moved out of a project).

Sometimes it can lead to SPAM flood on Slack notification channel.
The possible solution is to have a possibility to configure which type of actions should trigger a new notification to the configured Slack channel e.g. _send notification when new issue has been created only_

**Comment by infojunkie** [comment]
Implemented, please try it.
