### ISSUE TITLE
Use of undefined constant ERROR_NO_CURL

### ISSUE THREAD

**Issue by webbird** [infojunkie/MantisBT-Slack#55]
I am getting this error:

'Use of undefined constant ERROR_NO_CURL - assumed 'ERROR_NO_CURL' (this will throw an Error in a future version of PHP)' in '<MANTISROOT>\plugins\Slack\Slack.php' line 43

I can fix the error itself (=enable CURL), of course, but you may want to fix *this*. ;)

MantisBT-Version | 2.24.2
PHP-Version | 7.4.1

**Comment by infojunkie** [comment]
Thanks! What do you suggest to fix it?

**Comment by infojunkie** [comment]
Thanks for the report!

**Comment by webbird** [comment]
This was really fast, thank you!
